FROM python:3.11-slim

WORKDIR /app

COPY requirements.render.txt .
RUN pip install --no-cache-dir -r requirements.render.txt

COPY . .

# Leapcell uses PORT env
ENV APP_HOST=0.0.0.0
ENV PYTHON_VERSION=3.11.0
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD python -m app.main
